#### general settings
name: train
use_tb_logger: true
model: srgan
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: training_datasetn
    mode: LWGT
    dataroot_GT: ./training_dataset/train/HR
    dataroot_LQ: ./training_dataset/train/edgemap
    dataroot_WF: ./training_dataset/train/WF

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 5
    GT_size: 256
    use_flip: true
    use_rot: true
#    color: RGB -> grey img input
  val:
    name: validate
    mode: LWGT
    dataroot_GT: ./training_dataset/test/HR
    dataroot_LQ: ./training_dataset/test/edgemap
    dataroot_WF: ./training_dataset/test/WF
#### network structures
network_G:
  which_model_G: RRDBNet #RCAN/RNAN/RRDBNet/UAN/DEFIAN/TTSR
  # in_nc for netG: LR+WF
  in_nc: 2   # for all
  out_nc: 1 #  for all
  nf: 64    #  for RRDB
  nb: 23    #  for RRDB
  #scale: 1 #for RNAN/RCAN


network_D:
  which_model_D: Unet
  in_nc: 1
  nf: 64

network_D2:
  which_model_D2: patch_GAN
  # in_nc for netD2: LR+WF+HR
  in_nc: 1
  nf: 64

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~
  pretrain_model_D: ~
  strict_load: true
  resume_state: ~
  pretrain_model_D2: ~
  strict_load: true
  resume_state: ~
#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-05
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-05
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [50000, 100000, 200000, 300000]
  #lr_steps: [150000, 200000,250000,300000]
  lr_gamma: 0.5
  pixel_criterion: ms_ssim_l1 #soft_skel_ssim
  pixel_weight: 1
  fft_weight: 0.01
  fm_criterion: l1
  fm_weight: 0
  feature_criterion: l1
  feature_weight: 0.01
  tpl_criterion: l2
  tpl_weight: 0
  gan_type: ragan  # gan | ragan
  gan_weight: 0.001 #!!float 2.5e-4

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: 100

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: 100
